import Link from "next/link";
import { BottomNav } from "@/components/bottom-nav";
import { createSupabaseServerClient } from "@/lib/supabase";

type Account={id:string;name:string;town:string|null;postcode:string|null;relationship_status:string|null;classification:string|null};
type Order={account_id:string;order_date:string;net_amount:number};
type Visit={account_id:string;completed_at:string};
type Container={account_id:string;off_site_days:number|null;lost:boolean};
type Row={account:Account;score:number;reason:string;revenue:number;orders:number;lastOrder:string|null;typicalGap:number|null;daysSince:number|null;overdueBy:number|null;trend:number|null;lastVisit:string|null;containerCount:number;oldestContainer:number;bucket:"slipping"|"lapsed"|"growth"|"containers"|"watch"};

export default async function SalesIntelligencePage(){
  const supabase=await createSupabaseServerClient();
  const [accountRows,orderRows,visitRows,containerRows]=await Promise.all([
    fetchAll<Account>(supabase,"accounts","id,name,town,postcode,relationship_status,classification",q=>q.neq("relationship_status","closed").order("name",{ascending:true})),
    fetchAll<Order>(supabase,"sales_orders","account_id,order_date,net_amount",q=>q.order("order_date",{ascending:true})),
    fetchAll<Visit>(supabase,"visits","account_id,completed_at",q=>q.order("completed_at",{ascending:true})),
    fetchAll<Container>(supabase,"account_containers_snapshot","account_id,off_site_days,lost",q=>q.order("account_id",{ascending:true})),
  ]);
  const byOrder=group(orderRows,"account_id"),byVisit=group(visitRows,"account_id"),byContainer=group(containerRows,"account_id");
  const now=new Date();const start90=new Date(now);start90.setDate(start90.getDate()-90);const prev90=new Date(start90);prev90.setDate(prev90.getDate()-90);
  const rows:Row[]=[];
  for(const account of accountRows){const os=(byOrder.get(account.id)||[]).sort((x,y)=>x.order_date.localeCompare(y.order_date));if(!os.length)continue;const revenue=os.reduce((s,o)=>s+Number(o.net_amount||0),0);const dates=os.map(o=>day(o.order_date));const gaps=dates.slice(1).map((d,i)=>(d.getTime()-dates[i].getTime())/86400000).filter(n=>n>=0);const typical=gaps.length?median(gaps):null;const last=os[os.length-1];const daysSince=Math.max(0,Math.floor((strip(now).getTime()-day(last.order_date).getTime())/86400000));const overdue=typical!==null?Math.max(0,Math.round(daysSince-typical)):null;
    const recent=os.filter(o=>day(o.order_date)>=start90).reduce((s,o)=>s+Number(o.net_amount||0),0);const prior=os.filter(o=>{const d=day(o.order_date);return d>=prev90&&d<start90}).reduce((s,o)=>s+Number(o.net_amount||0),0);const trend=prior>0?((recent-prior)/prior)*100:null;
    const visitsFor=(byVisit.get(account.id)||[]).sort((a,b)=>a.completed_at.localeCompare(b.completed_at));const lastVisit=visitsFor.length?visitsFor[visitsFor.length-1].completed_at:null;const cs=(byContainer.get(account.id)||[]).filter(c=>!c.lost);const oldest=cs.reduce((m,c)=>Math.max(m,Number(c.off_site_days||0)),0);
    let score=Math.min(35,revenue/500);let bucket:Row["bucket"]="watch";let reason="Worth keeping warm";
    if(typical!==null&&daysSince>typical*1.35&&daysSince>21){score+=Math.min(40,(daysSince/Math.max(typical,1))*12);bucket="slipping";reason=`Usually orders every ${Math.round(typical)} days · now ${daysSince} days since last order`;}
    if(daysSince>90&&revenue>500){score+=22;bucket="lapsed";reason=`No order for ${daysSince} days · ${money(revenue)} sales in 2026`;}
    if(trend!==null&&trend<-25&&recent>0){score+=18;if(bucket==="watch")bucket="slipping";reason=`Recent 90-day sales down ${Math.abs(Math.round(trend))}% vs prior 90 days`;}
    if(trend!==null&&trend>35&&recent>500&&bucket==="watch"){score+=10;bucket="growth";reason=`Recent 90-day sales up ${Math.round(trend)}% · growth account`;}
    if(cs.length&&oldest>60){score+=Math.min(15,oldest/10);if(bucket==="watch")bucket="containers";reason=`${cs.length} containers on site · oldest ${oldest} days`;}
    if(account.relationship_status==="lapsed")score+=8;
    rows.push({account,score,revenue,orders:os.length,lastOrder:last.order_date,typicalGap:typical,daysSince,overdueBy:overdue,trend,lastVisit,containerCount:cs.length,oldestContainer:oldest,bucket,reason});
  }
  rows.sort((a,b)=>b.score-a.score||b.revenue-a.revenue);
  const visibleRows=rows.filter(r=>r.account.relationship_status!=="dormant");
  const dormantCount=rows.length-visibleRows.length;
  const top=visibleRows.slice(0,50);const slipping=visibleRows.filter(r=>r.bucket==="slipping").length;const lapsed=visibleRows.filter(r=>r.bucket==="lapsed").length;const containersDue=visibleRows.filter(r=>r.oldestContainer>60).length;const active=visibleRows.filter(r=>(r.daysSince??999)<=60).length;
  return <div className="min-h-screen bg-slate-50 pb-24 text-slate-950 md:pb-10"><BottomNav active="Sales"/><main className="mx-auto max-w-6xl px-4 py-5 sm:px-6"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">Sales intelligence</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Who should we contact today?</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Ranked from ViewPlan sales history, CRM activity and container signals. Closed and dormant accounts are kept out of the normal targeting queue.</p></div></div>
  <section className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Kpi label="Slipping" value={String(slipping)}/><Kpi label="Lapsed value" value={String(lapsed)}/><Kpi label="Containers >60d" value={String(containersDue)}/><Kpi label="Active ≤60d" value={String(active)}/></section>
  <div className="mt-5 flex flex-wrap gap-2">{[["All",visibleRows.length],["Slipping",slipping],["Lapsed",lapsed],["Growing",visibleRows.filter(r=>r.bucket==="growth").length],["Containers",visibleRows.filter(r=>r.bucket==="containers").length],["Dormant hidden",dormantCount]].map(([label,count])=><span key={String(label)} className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-600">{label} · {count}</span>)}</div>
  <section className="mt-5 space-y-3">{top.map((r,i)=><article key={r.account.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex items-start gap-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-950 text-xs font-bold text-white">{i+1}</div><div className="min-w-0 flex-1"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Link href={`/accounts/${r.account.id}`} className="text-lg font-semibold hover:underline">{r.account.name}</Link><Badge bucket={r.bucket}/></div><p className="mt-1 text-sm text-slate-500">{[r.account.classification,r.account.town,r.account.postcode].filter(Boolean).join(" · ")}</p></div><div className="text-left sm:text-right"><p className="font-semibold">{money(r.revenue)} YTD</p><p className="mt-1 text-xs text-slate-400">{r.orders} orders</p></div></div><div className="mt-3 rounded-xl bg-slate-50 p-3"><p className="text-sm font-semibold text-slate-800">{r.reason}</p><p className="mt-1 text-xs text-slate-500">Last order {r.lastOrder?date(r.lastOrder):"—"}{r.lastVisit?` · last visit ${date(r.lastVisit)}`:""}{r.containerCount?` · ${r.containerCount} containers on site`:""}</p></div><div className="mt-3 flex flex-wrap gap-2"><Link href={`/accounts/${r.account.id}`} className="rounded-xl bg-slate-950 px-3 py-2 text-xs font-semibold text-white">Open account</Link><Link href={`/accounts/${r.account.id}/appointment`} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold">Book appointment</Link><Link href={`/accounts/${r.account.id}/sales`} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold">View sales</Link></div></div></div></article>)}</section>
  </main></div>;
}
async function fetchAll<T>(client:any,table:string,select:string,apply:(q:any)=>any){const out:T[]=[];const size=1000;for(let from=0;;from+=size){let q=client.from(table).select(select);q=apply(q).range(from,from+size-1);const {data,error}=await q;if(error)throw error;out.push(...((data||[]) as T[]));if(!data||data.length<size)return out;}}
function group<T extends Record<string,any>>(rows:T[],key:keyof T){const m=new Map<string,T[]>();for(const r of rows){const k=String(r[key]||"");if(!k)continue;if(!m.has(k))m.set(k,[]);m.get(k)!.push(r)}return m}function median(v:number[]){const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}function day(v:string){return new Date(`${v.slice(0,10)}T00:00:00`)}function strip(d:Date){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}function money(v:number){return new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(v)}function date(v:string){return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short"}).format(new Date(v))}function Kpi({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[11px] font-medium uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-2xl font-semibold tracking-tight">{value}</p></div>}function Badge({bucket}:{bucket:Row["bucket"]}){const labels={slipping:"Slipping",lapsed:"Lapsed value",growth:"Growing",containers:"Containers",watch:"Watch"};return <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-slate-600">{labels[bucket]}</span>}
