"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import type {AccountSellingRow} from "@/lib/account-selling";

export function AvailabilitySelector({accountId,rows,loaded}:{accountId:string;rows:AccountSellingRow[];loaded:boolean}){
 const [format,setFormat]=useState("all");const [query,setQuery]=useState("");const [selected,setSelected]=useState<Set<string>>(new Set());
 const visible=useMemo(()=>{const term=query.trim().toLowerCase();return rows.filter(row=>(format==="all"||row.broadFormat===format)&&(!term||[row.productName,row.packageLabel].some(value=>value.toLowerCase().includes(term))))},[rows,format,query]);
 function toggle(id:string){setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next})}
 const emailHref=`/accounts/${accountId}/quick-price-email?variants=${encodeURIComponent([...selected].join(","))}`;
 return <><div className="mt-5 flex flex-wrap gap-2">{["all","cask","keg","can"].map(value=><button key={value} type="button" onClick={()=>setFormat(value)} className={`rounded-full px-4 py-2 text-sm font-semibold ring-1 ring-inset ${format===value?"bg-slate-950 text-white ring-slate-950":"bg-white ring-slate-200"}`}>{cap(value)}</button>)}</div><label className="mt-3 block"><span className="sr-only">Search products</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search beer…" className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3"/></label><section className="mt-5 space-y-3">{visible.map(row=><label key={row.variantId} className={`block cursor-pointer rounded-2xl border bg-white p-4 shadow-sm sm:p-5 ${selected.has(row.variantId)?"border-slate-950 ring-1 ring-slate-950":"border-slate-200"}`}><div className="flex gap-3"><input type="checkbox" checked={selected.has(row.variantId)} onChange={()=>toggle(row.variantId)} className="mt-1 h-5 w-5 shrink-0 accent-slate-950"/>{row.imageUrl?<img src={row.imageUrl} alt="" className="h-16 w-16 shrink-0 rounded-xl object-cover"/>:null}<div className="min-w-0 flex-1"><div className="flex flex-col gap-1 sm:flex-row sm:justify-between"><div><h2 className="text-lg font-semibold">{row.productName}</h2><p className="text-sm text-slate-500">{row.packageLabel}{row.abv!=null?` · ${row.abv}% ABV`:""}</p></div><p className="font-semibold">{row.availableQuantity} available</p></div>{row.description?<p className="mt-2 line-clamp-2 text-sm text-slate-600">{row.description}</p>:null}<div className="mt-3 flex items-end justify-between gap-4"><div><p className="text-[10px] uppercase text-slate-400">Your price</p><p className="text-lg font-semibold">{moneyOrDash(row.customerPrice??row.listPrice)}</p></div>{row.listPrice!=null&&row.customerPrice!==row.listPrice?<p className="text-xs text-slate-400">List {moneyOrDash(row.listPrice)}</p>:null}</div></div></div></label>)}{!visible.length?<div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">{loaded?"No available products match this customer’s packaging rules and filter.":"Availability has not been loaded yet."}</div>:null}</section><div className="sticky bottom-20 mt-5 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur md:bottom-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{selected.size} product{selected.size===1?"":"s"} selected</p>{selected.size?<Link href={emailHref} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Send availability</Link>:<span className="rounded-xl bg-slate-200 px-4 py-3 text-sm font-semibold text-slate-500">Select products</span>}</div></div></>;
}
function cap(value:string){return value==="all"?"All":value[0].toUpperCase()+value.slice(1)}
function moneyOrDash(value:number|null){return value==null?"—":new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(value)}
