import Link from "next/link";
import { notFound } from "next/navigation";
import { BottomNav } from "@/components/bottom-nav";
import { createSupabaseServerClient } from "@/lib/supabase";

type Container={id:string;viewplan_item_no:string;container_type:string;contents:string|null;gyle:string|null;off_site_date:string|null;off_site_days:number|null;order_no:string|null;usage_count:number|null;leased:boolean|null;lease_expiry:string|null;lost:boolean;comment:string|null};

export default async function AccountContainersPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const supabase=await createSupabaseServerClient();
 const {data:account}=await supabase.from("accounts").select("id,name,town,postcode").eq("id",id).single();if(!account)notFound();
 const {data,error}=await supabase.from("account_containers_snapshot").select("id,viewplan_item_no,container_type,contents,gyle,off_site_date,off_site_days,order_no,usage_count,leased,lease_expiry,lost,comment").eq("account_id",id).order("off_site_days",{ascending:false,nullsFirst:false});if(error)throw error;
 const rows=(data||[]) as Container[];const active=rows.filter(r=>!r.lost);const oldest=active.reduce((m,r)=>Math.max(m,Number(r.off_site_days||0)),0);const over30=active.filter(r=>(r.off_site_days||0)>30).length;const over60=active.filter(r=>(r.off_site_days||0)>60).length;const over90=active.filter(r=>(r.off_site_days||0)>90).length;const lost=rows.filter(r=>r.lost).length;
 return <div className="min-h-screen bg-slate-50 pb-24 text-slate-950 md:pb-10"><header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-5xl px-4 py-4 sm:px-6"><Link href={`/accounts/${id}`} className="text-sm font-medium text-slate-500">← {account.name}</Link><h1 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">Containers on site</h1><p className="mt-1 text-sm text-slate-500">ViewPlan packaging snapshot · {[account.town,account.postcode].filter(Boolean).join(" · ")}</p></div></header><main className="mx-auto max-w-5xl space-y-4 px-4 py-4 sm:px-6">
 <section className="grid grid-cols-2 gap-3 sm:grid-cols-5"><Metric label="Active" value={String(active.length)}/><Metric label="Oldest" value={active.length?`${oldest} days`:"—"}/><Metric label=">30 days" value={String(over30)}/><Metric label=">60 days" value={String(over60)}/><Metric label=">90 days" value={String(over90)}/></section>
 {lost>0&&<div className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600"><span className="font-semibold text-slate-900">{lost} marked lost</span> in the current ViewPlan snapshot. These are shown below but excluded from overdue counts.</div>}
 <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold uppercase tracking-[0.08em] text-slate-500">Tracked containers ({rows.length})</h2><span className="text-xs text-slate-400">Oldest first</span></div>{rows.length?<div className="divide-y divide-slate-100">{rows.map(r=><div key={r.id} className="py-3 first:pt-0 last:pb-0"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{r.container_type} · {r.viewplan_item_no}</p>{r.lost&&<Badge text="Lost"/>}{r.leased&&<Badge text="Leased"/>}{!r.lost&&(r.off_site_days||0)>90&&<Badge text=">90d"/>}</div><p className="mt-1 text-sm text-slate-600">{r.contents||"Contents not recorded"}{r.gyle?` · ${r.gyle}`:""}</p><p className="mt-1 text-xs text-slate-500">{r.off_site_date?`Off site ${date(r.off_site_date)}`:"Off-site date unknown"}{r.order_no?` · order ${r.order_no}`:""}{r.usage_count!==null?` · used ${r.usage_count}x`:""}</p>{r.comment&&<p className="mt-1 text-xs text-slate-400">{r.comment}</p>}</div><div className="shrink-0 text-right"><p className="text-lg font-semibold">{r.off_site_days??"—"}</p><p className="text-[10px] uppercase tracking-wide text-slate-400">days</p></div></div></div>)}</div>:<p className="text-sm text-slate-500">No containers are currently matched to this account.</p>}</section>
 </main><BottomNav active="Accounts"/></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[11px] font-medium uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-xl font-semibold tracking-tight">{value}</p></div>};function Badge({text}:{text:string}){return <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-slate-600">{text}</span>};function date(v:string){return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${v.slice(0,10)}T00:00:00`))}
