import {RoutePlanner} from "./route-planner";
import {mapOrder,type AccountLocation} from "@/lib/fulfilment";
import Link from "next/link";
import {createSupabaseServerClient} from "@/lib/supabase";
import {orderWeight,isSourceStale,monday,addDays,type SourceOrder,type Vehicle,type OrderPlan} from "@/lib/fulfilment";
import {savePlan} from "./actions";
export const dynamic="force-dynamic";
const field="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm";
const kg=(n:number)=>new Intl.NumberFormat("en-GB",{maximumFractionDigits:1}).format(n)+" kg";
export default async function Page({searchParams}:{searchParams:Promise<{week?:string;history?:string;error?:string;saved?:string}>}){
 const params=await searchParams;const db=await createSupabaseServerClient();
 const requestTime=new Date();
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).format(requestTime);
 let start=monday(today);try{if(params.week)start=monday(params.week);}catch{}
 const end=addDays(start,21);const now=requestTime.getTime();
 const [syncResult,planResult]=await Promise.all([db.from("fulfilment_sync").select("*").single(),db.from("fulfilment_plans").select("*").order("source_id").limit(10000)]);
 if(syncResult.error||planResult.error)throw new Error("Fulfilment data is unavailable. Check the pilot migration and retry.");
 if(planResult.data.length===10000)throw new Error("Planning scope exceeded; narrow the source retention before continuing.");
 const state=syncResult.data;const vehicles=state.vehicles as Vehicle[];const plans=new Map((planResult.data as OrderPlan[]).map(p=>[p.source_id,p]));
 const orders:SourceOrder[]=[];
 for(let from=0;from<10000;from+=500){const r=await db.from("fulfilment_orders").select("*").order("source_id").range(from,from+499);if(r.error)throw new Error("Order snapshot unavailable");orders.push(...r.data as SourceOrder[]);if(r.data.length<500)break;if(from===9500)throw new Error("Order scope exceeded; source retention needs review.");}
 const items=orders.map(o=>{const plan=plans.get(o.source_id);return {o,plan,date:plan?.planned_date||o.delivery_date,vehicle:plan?plan.vehicle_id:o.fulfilment_method==="pallet"?3:o.snapshot.header.delivery_vehicle_id,weight:orderWeight(o.snapshot.lines)};}).filter(x=>(!x.date||(x.date>=start&&x.date<end))&&(params.history==="1"||(!x.o.snapshot.header.is_cancelled&&!x.o.snapshot.header.is_deleted)));
 const groups=new Map<string,typeof items>();for(const item of items){const key=(item.date||"Unscheduled")+"|"+(item.vehicle??"Unassigned");groups.set(key,[...(groups.get(key)||[]),item]);}
 const locations=new Map<string,AccountLocation>();const accountIds=[...new Set(items.map(i=>i.o.account_id).filter((id):id is string=>!!id))];
 for(let from=0;from<accountIds.length;from+=200){const result=await db.from("accounts").select("id,address_line_1,town,postcode,latitude,longitude").in("id",accountIds.slice(from,from+200));if(result.error)throw new Error("Account locations unavailable");for(const a of result.data)locations.set(a.id,a as AccountLocation);}
 const mapOrders=items.filter(i=>!i.o.snapshot.header.is_cancelled&&!i.o.snapshot.header.is_deleted).map(i=>mapOrder(i.o,i.plan,locations.get(i.o.account_id||""),vehicles,now));
 const stale=!!state.last_error||isSourceStale(state.observed_at,now);
 return <main className="mx-auto max-w-6xl space-y-6 px-4 pb-20 pt-20 text-slate-950">
 <header><Link href="/sales" className="text-sm underline">← Sales</Link><h1 className="mt-3 text-3xl font-semibold">Weekly fulfilment</h1><p className="mt-2 text-slate-600">Planning pilot · Orders and allocation remain in ViewPlan. These are provisional day and vehicle assignments.</p></header>
 <section className={`rounded-xl border p-4 ${stale?"border-amber-400 bg-amber-50":"border-slate-200 bg-white"}`}><p className="font-semibold">{state.observed_at?"Last order read: "+new Date(state.observed_at).toLocaleString("en-GB",{timeZone:"Europe/London"}):"Awaiting the first order connector run"}</p><p className="text-sm">Poll every 30 minutes. {stale?"Source needs attention; retain and review the last known plan.":"Source within the 45-minute freshness allowance."} {state.last_error}</p><p className="mt-2 text-sm">Weight totals cover known outbound goods only. Return loads, space and four-hour driving limits are not yet validated. Final routing is unavailable in this pilot.</p></section>
 {params.error&&<p role="alert" className="rounded-xl bg-red-50 p-4">{params.error}</p>}{params.saved&&<p role="status">Provisional assignment saved. ViewPlan has not been changed.</p>}
 <form className="flex flex-wrap items-end gap-3"><label className="text-sm">Week starting<input type="date" name="week" defaultValue={start} className={field+" ml-2"}/></label><label className="text-sm"><input type="checkbox" name="history" value="1" defaultChecked={params.history==="1"}/> Include cancelled/deleted</label><button className={field}>Show three weeks</button><Link href={`/fulfilment?week=${addDays(start,-7)}`} className={field}>Previous week</Link><Link href={`/fulfilment?week=${addDays(start,7)}`} className={field}>Next week</Link></form>
 <RoutePlanner key={start+JSON.stringify(mapOrders.map(o=>[o.id,o.sourceRevision,o.planRevision]))} orders={mapOrders} start={start} initialDay={today>=start&&today<end?today:start} vehicles={vehicles} refreshError={!!state.last_error}/>
 <p>{items.length} orders · {start} to {addDays(end,-1)}. Source delivery flags are shown as allocation context, not proof of delivery.</p>
 {!items.length&&<p className="rounded-xl border border-dashed p-8">No imported orders in this period. Run the order connector or choose another week.</p>}
 {[...groups.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([key,rows])=>{const v=vehicles.find(v=>v.vehicle_id===rows[0].vehicle);const sum=rows.reduce((n,r)=>n+r.weight.knownKg,0);const unknown=rows.some(r=>r.weight.totalKg===null);const max=v?.vehicle_max_load_kg||0;return <section key={key} className="rounded-2xl border border-slate-200 bg-white p-4"><h2 className="text-xl font-semibold">{rows[0].date||"Unscheduled"} · {v?.vehicle_name||"Unassigned / unknown vehicle"}</h2><p className={`mt-1 ${max&&sum>max?"font-bold text-red-700":"text-slate-600"}`}>{kg(sum)} known outbound {unknown?"· incomplete weight":""}{max?` · ${kg(max)} source payload`:" · no van payload applicable/confirmed"}{max&&sum>max?" · OVER PAYLOAD":""}</p><p className="mb-4 text-xs text-slate-500">Daily grouping, not a validated run or proof that one load fits.</p>
 <div className="grid gap-3 lg:grid-cols-2">{rows.map(({o,plan,date,vehicle,weight})=>{const h=o.snapshot.header;const c=o.snapshot.customer;const status=o.snapshot.customer_status;return <article id={`order-${o.source_id}`} key={o.source_id} className="rounded-xl border p-4"><div className="flex justify-between gap-2"><h3 className="font-semibold">{o.account_id?<Link href={`/accounts/${o.account_id}`} className="underline">{c.customer_name}</Link>:c.customer_name}</h3><span>Order {h.order_no_val||o.source_id}</span></div><p className="text-sm text-slate-600">{c.delivery_address?.trim()||[c.customer_address_line1,c.customer_address_town,c.customer_address_postcode].filter(Boolean).join(", ")}</p>
 <p className="mt-2 text-xs uppercase text-slate-500">{o.fulfilment_method.replaceAll("_"," ")} · Provisional</p><p className="mt-2 font-semibold">{weight.totalKg===null?kg(weight.knownKg)+" known; total unresolved":kg(weight.totalKg)}</p>
 <ul className="text-sm text-amber-800">{weight.issues.map(i=><li key={i}>{i}</li>)}{!o.account_id&&<li>Account mapping missing</li>}{h.order_type!==1&&<li>Source order type needs classification</li>}{h.is_pre_order&&<li>Pre-order · confirm commitment</li>}{(h.is_cancelled||h.is_deleted)&&<li>Cancelled/deleted in source</li>}{(h.order_exclude_from_dlv_sched||c.customer_exclude_from_dlv_sched)&&<li>Excluded from source delivery schedule · review</li>}{status?.allow_order_dispatch!==true&&<li>{status?.allow_order_dispatch===false?"Dispatch blocked by customer status":"Customer dispatch permission unknown"}</li>}{status?.allow_order===false&&<li>Ordering blocked</li>}{isSourceStale(o.observed_at,now)&&<li>Order observation stale or missing from latest read</li>}{plan&&plan.reviewed_source_revision!==o.revision&&<li>Source changed since this assignment · review quantities and weight</li>}</ul>
 <details className="mt-2"><summary className="cursor-pointer text-sm">Lines and source context</summary><ul className="mt-2 text-sm">{o.snapshot.lines.map(l=><li key={l.order_item_id}>{l.quantity} × {l.product_name||"Item"} · {l.packaging_type}{l.is_cancelled||l.is_deleted?" (cancelled/deleted)":""}</li>)}</ul><p className="text-xs">Revision {o.revision} · source dispatched: {String(h.is_dispatched)} · source delivered: {String(h.is_delivered)}</p></details>
 {!h.is_cancelled&&!h.is_deleted&&<form action={savePlan} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="source" value={o.source_id}/><input type="hidden" name="source_revision" value={o.revision}/><input type="hidden" name="plan_revision" value={plan?.revision||0}/><input type="hidden" name="week" value={start}/><input aria-label={`Planning date for order ${h.order_no_val}`} type="date" required name="date" defaultValue={date||""} className={field}/><select aria-label={`Vehicle for order ${h.order_no_val}`} name="vehicle" defaultValue={vehicle??""} className={field}><option value="">Unassigned</option>{vehicles.filter(v=>v.is_available&&(o.fulfilment_method!=="pallet"||v.vehicle_id===3)).map(v=><option key={v.vehicle_id} value={v.vehicle_id}>{v.vehicle_name}</option>)}</select><button className="rounded-lg bg-slate-950 px-3 py-2 text-sm text-white">Save provisional</button></form>}
 </article>;})}</div></section>;})}
 </main>;
}
