import Link from "next/link";
import { notFound } from "next/navigation";
import { BottomNav } from "@/components/bottom-nav";
import { createSupabaseServerClient } from "@/lib/supabase";

type Order={id:string;viewplan_order_no:string;order_date:string;delivery_date:string|null;sales_channel:string|null;net_amount:number;total_litres:number;invoice_no:string|null};
type Line={order_id:string;product_name:string|null;package_type:string|null;quantity:number|null;total_litres:number|null;net_after_discount:number|null;line_type:string};

export default async function AccountSalesPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const supabase=await createSupabaseServerClient();
 const {data:account}=await supabase.from("accounts").select("id,name,town,postcode").eq("id",id).single();if(!account)notFound();
 const {data:orders,error}=await supabase.from("sales_orders").select("id,viewplan_order_no,order_date,delivery_date,sales_channel,net_amount,total_litres,invoice_no").eq("account_id",id).order("order_date",{ascending:false});if(error)throw error;
 const orderRows=(orders||[]) as Order[];const ids=orderRows.map(o=>o.id);let lines:Line[]=[];
 for(let i=0;i<ids.length;i+=200){const batch=ids.slice(i,i+200);if(!batch.length)continue;const {data,error:lineError}=await supabase.from("sales_order_lines").select("order_id,product_name,package_type,quantity,total_litres,net_after_discount,line_type").in("order_id",batch);if(lineError)throw lineError;lines.push(...((data||[]) as Line[]));}
 const revenue=orderRows.reduce((s,o)=>s+Number(o.net_amount||0),0);const litres=orderRows.reduce((s,o)=>s+Number(o.total_litres||0),0);const avg=orderRows.length?revenue/orderRows.length:0;const sellar=orderRows.filter(o=>(o.sales_channel||"").toLowerCase()==="sellar").length;
 const orderDates=orderRows.map(o=>new Date(`${o.order_date}T00:00:00`).getTime()).sort((a,b)=>a-b);const gaps=orderDates.slice(1).map((d,i)=>(d-orderDates[i])/86400000);const typicalGap=gaps.length?median(gaps):null;
 const products=new Map<string,{revenue:number;qty:number;litres:number}>();for(const l of lines){if(l.line_type!=="product"||!l.product_name)continue;const p=products.get(l.product_name)||{revenue:0,qty:0,litres:0};p.revenue+=Number(l.net_after_discount||0);p.qty+=Number(l.quantity||0);p.litres+=Number(l.total_litres||0);products.set(l.product_name,p);}const topProducts=[...products.entries()].sort((a,b)=>b[1].revenue-a[1].revenue).slice(0,10);
 const linesByOrder=new Map<string,Line[]>();for(const l of lines){if(!linesByOrder.has(l.order_id))linesByOrder.set(l.order_id,[]);linesByOrder.get(l.order_id)!.push(l);}
 return <div className="min-h-screen bg-slate-50 pb-24 text-slate-950 md:pb-10"><header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-5xl px-4 py-4 sm:px-6"><Link href={`/accounts/${id}`} className="text-sm font-medium text-slate-500">← {account.name}</Link><h1 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">Sales history</h1><p className="mt-1 text-sm text-slate-500">ViewPlan order history · {[account.town,account.postcode].filter(Boolean).join(" · ")}</p></div></header><main className="mx-auto max-w-5xl space-y-4 px-4 py-4 sm:px-6">
 <section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="2026 sales" value={money(revenue)}/><Metric label="Orders" value={String(orderRows.length)}/><Metric label="Average order" value={money(avg)}/><Metric label="Volume" value={`${Math.round(litres).toLocaleString("en-GB")} L`}/></section>
 <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-4 sm:grid-cols-3"><Info label="Last order" value={orderRows[0]?date(orderRows[0].order_date):"—"}/><Info label="Typical order gap" value={typicalGap===null?"—":`${Math.round(typicalGap)} days`}/><Info label="Sellar orders" value={`${sellar} of ${orderRows.length}`}/></div></section>
 <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><h2 className="mb-4 text-sm font-semibold uppercase tracking-[0.08em] text-slate-500">Top products by sales</h2>{topProducts.length?<div className="divide-y divide-slate-100">{topProducts.map(([name,p])=><div key={name} className="grid grid-cols-[1fr_auto] gap-4 py-3 first:pt-0 last:pb-0"><div><p className="font-semibold">{name}</p><p className="mt-0.5 text-xs text-slate-500">{Math.round(p.qty)} packs/containers · {Math.round(p.litres).toLocaleString("en-GB")} L</p></div><p className="font-semibold">{money(p.revenue)}</p></div>)}</div>:<p className="text-sm text-slate-500">No product history imported.</p>}</section>
 <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><h2 className="mb-4 text-sm font-semibold uppercase tracking-[0.08em] text-slate-500">Orders</h2>{orderRows.length?<div className="space-y-3">{orderRows.map(o=>{const ol=(linesByOrder.get(o.id)||[]).filter(l=>l.line_type==="product");return <details key={o.id} className="group rounded-xl border border-slate-200 bg-slate-50 open:bg-white"><summary className="cursor-pointer list-none p-3"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">Order {o.viewplan_order_no}</p>{o.sales_channel&&<span className="rounded-full bg-white px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-slate-500 ring-1 ring-slate-200">{o.sales_channel}</span>}</div><p className="mt-1 text-xs text-slate-500">{date(o.order_date)}{o.delivery_date?` · delivered ${date(o.delivery_date)}`:""} · {Math.round(Number(o.total_litres||0))} L</p></div><div className="text-right"><p className="font-semibold">{money(Number(o.net_amount||0))}</p><p className="mt-1 text-xs text-slate-400">{ol.length} product line{ol.length===1?"":"s"} ▾</p></div></div></summary><div className="border-t border-slate-200 px-3 pb-3"><div className="divide-y divide-slate-100">{ol.map((l,i)=><div key={`${o.id}-${i}`} className="flex items-start justify-between gap-4 py-2.5"><div><p className="text-sm font-medium">{l.product_name}</p><p className="text-xs text-slate-500">{l.package_type||"—"} · qty {Number(l.quantity||0).toLocaleString("en-GB")} · {Math.round(Number(l.total_litres||0))} L</p></div><p className="text-sm font-semibold">{money(Number(l.net_after_discount||0))}</p></div>)}</div></div></details>})}</div>:<p className="text-sm text-slate-500">No ViewPlan sales history has been imported for this account.</p>}</section>
 </main><BottomNav active="Accounts"/></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[11px] font-medium uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-xl font-semibold tracking-tight">{value}</p></div>};function Info({label,value}:{label:string;value:string}){return <div><p className="text-[11px] font-medium uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-semibold">{value}</p></div>};function money(v:number){return new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(v)}function date(v:string){return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${v.slice(0,10)}T00:00:00`))}function median(v:number[]){const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
