import Link from "next/link";
import { AccountContactAction } from "@/components/account-contact-action";
import { AccountLiveSearch } from "@/components/account-live-search";
import { AutoSubmitSelect } from "@/components/auto-submit-select";
import { BottomNav } from "@/components/bottom-nav";
import { createSupabaseServerClient } from "@/lib/supabase";
import { updateWeeklyProgress } from "./actions";

type Named = { id: string; name: string };
type Plan = { id:string; week_start:string; title:string; message:string; status:string; territories:{territory:Named|Named[]|null}[]; products:{product:Named|Named[]|null}[] };
type Contact = { id:string; full_name:string|null; email:string|null; phone:string|null; mobile:string|null; is_primary:boolean; active:boolean };
type SalesSnapshot = { last_order_date:string|null };
type Account = { id:string; name:string; town:string|null; relationship_status:string; phone?:string|null; mobile?:string|null; email?:string|null; territory?:Named|Named[]|null; contacts?:Contact[]|null; sales?:SalesSnapshot|SalesSnapshot[]|null };
type Progress = { account_id:string; status:string };
type ActionRow = { id:string; title?:string; purpose?:string|null; due_at?:string|null; starts_at?:string; account:Account|Account[]|null };

export default async function SalesHome({ searchParams }: { searchParams: Promise<{ q?:string; territory?:string; list?:string }> }) {
  const { q = "", territory = "", list = "open" } = await searchParams;
  const supabase = await createSupabaseServerClient();
  const { data: auth } = await supabase.auth.getUser();
  const userId = auth.user!.id;
  const now = new Date(); const todayStart = startOfDay(now); const tomorrow = new Date(todayStart); tomorrow.setDate(tomorrow.getDate()+1);
  const { data: planRows, error: planError } = await supabase.from("weekly_sales_plans").select("id,week_start,title,message,status,territories:weekly_sales_plan_territories(territory:territories(id,name)),products:weekly_sales_plan_products(product:products(id,name))").eq("status", "active").order("week_start", { ascending:true }).limit(20);
  if (planError) throw new Error(planError.message);
  const plan = choosePlan((planRows || []) as Plan[], now);
  const planTerritories = plan ? plan.territories.map((row) => one(row.territory)).filter((item): item is Named => Boolean(item)).sort((a,b)=>a.name.localeCompare(b.name)) : [];
  const territoryIds = planTerritories.map(item=>item.id);
  const selectedTerritoryIds = territory && territoryIds.includes(territory) ? [territory] : territoryIds;

  const workingPromise = plan && selectedTerritoryIds.length ? supabase.from("accounts").select("id,name,town,relationship_status,phone,mobile,email,territory:territories(id,name),contacts(id,full_name,email,phone,mobile,is_primary,active),sales:account_sales_snapshot(last_order_date)").in("territory_id", selectedTerritoryIds).eq("sales_service_model", "territory").eq("active", true).or("brewery_available.is.null,brewery_available.eq.true").not("relationship_status", "in", "(closed,dormant)").order("name", { referencedTable:"territories", ascending:true }).order("name", { ascending:true }).limit(60) : Promise.resolve({ data: [], error:null });
  const progressPromise = plan ? supabase.from("weekly_sales_account_progress").select("account_id,status").eq("plan_id", plan.id) : Promise.resolve({ data: [], error:null });
  const managedTasksPromise = supabase.from("tasks").select("id,title,due_at,account:accounts!inner(id,name,town,relationship_status,sales_service_model)").eq("status", "open").eq("account.sales_service_model", "managed").lte("due_at", tomorrow.toISOString()).order("due_at").limit(8);
  const managedAppointmentsPromise = supabase.from("appointments").select("id,purpose,starts_at,account:accounts!inner(id,name,town,relationship_status,sales_service_model)").eq("status", "planned").eq("account.sales_service_model", "managed").gte("starts_at", todayStart.toISOString()).lt("starts_at", tomorrow.toISOString()).order("starts_at").limit(8);
  const myTasksPromise = supabase.from("tasks").select("id,title,due_at,account:accounts(id,name,town,relationship_status)").eq("assigned_to", userId).eq("status", "open").lte("due_at", tomorrow.toISOString()).order("due_at").limit(8);
  const myAppointmentsPromise = supabase.from("appointments").select("id,purpose,starts_at,account:accounts(id,name,town,relationship_status)").eq("assigned_to", userId).eq("status", "planned").gte("starts_at", todayStart.toISOString()).lt("starts_at", tomorrow.toISOString()).order("starts_at").limit(8);
  let searchPromise: PromiseLike<{data:unknown[]|null;error:unknown}> = Promise.resolve({ data:[], error:null });
  if (q.trim()) { const safe=q.replace(/[,%()]/g," ").trim(); searchPromise=supabase.from("accounts").select("id,name,town,relationship_status").or("brewery_available.is.null,brewery_available.eq.true").or(`name.ilike.%${safe}%,town.ilike.%${safe}%,postcode.ilike.%${safe}%`).order("name").limit(8); }
  const [workingResult, progressResult, managedTasks, managedAppointments, myTasks, myAppointments, searchResult] = await Promise.all([workingPromise, progressPromise, managedTasksPromise, managedAppointmentsPromise, myTasksPromise, myAppointmentsPromise, searchPromise]);
  if (workingResult.error || progressResult.error) throw new Error(String(workingResult.error || progressResult.error));
  const accounts = ((workingResult.data || []) as Account[]).sort(compareAccounts); const progress = new Map<string,ProgressStatus>(((progressResult.data || []) as Progress[]).map((row) => [row.account_id,isProgressStatus(row.status)?row.status:"not_contacted"]));
  const visibleAccounts = list === "all" ? accounts : accounts.filter(account=>["not_contacted","follow_up"].includes(progress.get(account.id)||"not_contacted"));
  const counts = accounts.reduce((result, account) => { result[progress.get(account.id) || "not_contacted"]++; return result; }, {not_contacted:0,contacted:0,follow_up:0,complete:0} as Record<ProgressStatus,number>);
  const managed = [...((managedTasks.data||[]) as ActionRow[]), ...((managedAppointments.data||[]) as ActionRow[])]; const mine = [...((myTasks.data||[]) as ActionRow[]), ...((myAppointments.data||[]) as ActionRow[])];

  return <div className="min-h-screen bg-slate-50 pb-24 text-slate-950 md:pb-8"><header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-5xl px-4 py-5 sm:px-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Sales workspace</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">This week</h1></div><Link href={plan?`/sales/edit?id=${plan.id}`:"/sales/edit"} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">{plan?"Edit focus":"Plan week"}</Link></div><div className="mt-5"><AccountLiveSearch initialValue={q}/>{q.trim() && <SearchResults query={q} accounts={(searchResult.data||[]) as Account[]}/>}</div></div></header>
    <main className="mx-auto max-w-5xl space-y-6 px-4 py-5 sm:px-6">{plan ? <><section className="rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">{formatWeek(plan.week_start)}</p><h2 className="mt-2 text-xl font-semibold">{plan.title}</h2>{plan.message&&<p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">{plan.message}</p>}<div className="mt-4 flex flex-wrap gap-2">{plan.products.map((r)=>one(r.product)).filter(Boolean).map((p)=><Chip key={p!.id}>{p!.name}</Chip>)}{plan.territories.map((r)=>one(r.territory)).filter(Boolean).map((t)=><Chip key={t!.id}>{t!.name}</Chip>)}</div></section>
      <section><div className="mb-3 flex items-end justify-between"><div><h2 className="text-lg font-semibold">Initial push</h2><p className="text-sm text-slate-500">Selected-area accounts · capped at 60</p></div><span className="text-sm font-semibold">{counts.not_contacted} remaining</span></div><div className="mb-4 grid grid-cols-4 gap-2"><Stat label="Total" value={accounts.length}/><Stat label="Contacted" value={counts.contacted+counts.complete}/><Stat label="Remaining" value={counts.not_contacted}/><Stat label="Follow-up" value={counts.follow_up}/></div><ListFilters territories={planTerritories} territory={territory} list={list} query={q}/>{visibleAccounts.length?<AccountGroups accounts={visibleAccounts} planId={plan.id} progress={progress}/>:<Empty>{accounts.length?"No open accounts match this filter.":"No eligible territory accounts match this plan."}</Empty>}</section></> : <Empty><strong>No active weekly plan.</strong><br/>Create one to give Sales a bounded, shared focus.</Empty>}
      <ActionSection title="Managed account actions" actions={managed} empty="No managed-account actions due."/><ActionSection title="My today" actions={mine} empty="Nothing due today."/>
    </main><BottomNav active="Sales"/></div>;
}

function AccountRow({account,planId,status}:{account:Account;planId:string;status:string}){const territory=one(account.territory);const contacts=(account.contacts||[]).filter(contact=>contact.active);const contact=contacts.find(item=>item.is_primary)||contacts[0];const phone=contact?.mobile||contact?.phone||account.mobile||account.phone||null;const email=contact?.email||account.email||null;const sales=one(account.sales||null);return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="truncate font-semibold">{account.name}</p><p className="mt-1 text-xs text-slate-500">{titleCase(account.relationship_status)} · {territory?.name||"Selected area"}{account.town?` · ${account.town}`:""}</p></div><Link href={`/accounts/${account.id}`} className="shrink-0 text-xs font-semibold text-slate-600 hover:underline">Open account →</Link></div><div className="mt-3 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-sm"><Meta label="Contact" value={contact?.full_name||"Account contact"}/><Meta label="Last order" value={formatOrderDate(sales?.last_order_date)}/><Meta label="Phone" value={phone||"Not recorded"}/><Meta label="Email" value={email||"Not recorded"}/></div><div className="mt-3 grid grid-cols-2 gap-2"><AccountContactAction accountId={account.id} type="call" target={phone} label="Call" weeklyPlanId={planId}/><AccountContactAction accountId={account.id} type="email" target={email} label="Email" weeklyPlanId={planId}/></div><form action={updateWeeklyProgress} className="mt-3 border-t border-slate-100 pt-3"><label className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wide text-slate-400" htmlFor={`progress-${account.id}`}>Weekly progress</label><div className="flex gap-2"><input type="hidden" name="plan_id" value={planId}/><input type="hidden" name="account_id" value={account.id}/><select id={`progress-${account.id}`} name="status" defaultValue={status} aria-label={`Weekly progress for ${account.name}`} className="h-10 min-w-0 flex-1 rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="not_contacted">Not contacted</option><option value="contacted">Contacted</option><option value="follow_up">Follow up</option><option value="complete">Complete</option></select><button className="h-10 rounded-xl bg-slate-100 px-3 text-sm font-semibold">Save</button></div></form></article>}
function AccountGroups({accounts,planId,progress}:{accounts:Account[];planId:string;progress:Map<string,ProgressStatus>}){const groups=new Map<string,Account[]>();for(const account of accounts){const name=one(account.territory)?.name||"No territory";groups.set(name,[...(groups.get(name)||[]),account])}return <div className="space-y-5">{[...groups.entries()].map(([territoryName,items])=><div key={territoryName}><div className="mb-2 flex items-center gap-2"><h3 className="text-sm font-semibold text-slate-700">{territoryName}</h3><span className="text-xs text-slate-400">{items.length}</span></div><div className="space-y-2">{items.map(account=><AccountRow key={account.id} account={account} planId={planId} status={progress.get(account.id)||"not_contacted"}/>)}</div></div>)}</div>}
function ListFilters({territories,territory,list,query}:{territories:Named[];territory:string;list:string;query:string}){return <form action="/sales" className="mb-4 grid grid-cols-2 gap-2"><input type="hidden" name="q" value={query}/><AutoSubmitSelect name="territory" value={territory} label="Filter by territory" options={[{value:"",label:"All territories"},...territories.map(item=>({value:item.id,label:item.name}))]}/><AutoSubmitSelect name="list" value={list} label="Filter weekly progress" options={[{value:"open",label:"Open only"},{value:"all",label:"All accounts"}]}/></form>}
function SearchResults({query,accounts}:{query:string;accounts:Account[]}){return <div className="mt-2 rounded-xl border border-slate-200 bg-white p-2 shadow-lg">{accounts.length?accounts.map(a=><Link key={a.id} href={`/accounts/${a.id}`} className="block rounded-lg px-3 py-2 text-sm hover:bg-slate-50"><span className="font-semibold">{a.name}</span><span className="ml-2 text-slate-400">{a.town}</span></Link>):<p className="p-3 text-sm text-slate-500">No matching accounts.</p>}<Link href={`/accounts?q=${encodeURIComponent(query)}`} className="block px-3 py-2 text-xs font-semibold text-slate-500">Open full account directory →</Link></div>}
function ActionSection({title,actions,empty}:{title:string;actions:ActionRow[];empty:string}){return <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">{title}</h2><span className="text-xs font-semibold text-slate-400">{actions.length}</span></div>{actions.length?<div className="space-y-2">{actions.map((action)=>{const account=one(action.account);return <Link key={`${action.starts_at?"a":"t"}-${action.id}`} href={account?`/accounts/${account.id}`:"/tasks"} className="block rounded-2xl border border-slate-200 bg-white p-4"><p className="font-semibold">{action.title||action.purpose||"Sales appointment"}</p><p className="mt-1 text-sm text-slate-500">{account?.name||"No account"} · {formatWhen(action.due_at||action.starts_at)}</p></Link>})}</div>:<Empty>{empty}</Empty>}</section>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-white p-3 text-center shadow-sm ring-1 ring-slate-200"><p className="text-xl font-semibold">{value}</p><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{label}</p></div>}
function Meta({label,value}:{label:string;value:string}){return <div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-0.5 truncate font-medium text-slate-700">{value}</p></div>}
function Empty({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-6 text-center text-sm text-slate-500">{children}</div>}
function Chip({children}:{children:React.ReactNode}){return <span className="rounded-full bg-white/10 px-3 py-1 text-xs font-semibold text-slate-200">{children}</span>}
function one<T>(value:T|T[]|null):T|null{return Array.isArray(value)?value[0]||null:value}
function startOfDay(date:Date){const next=new Date(date);next.setHours(0,0,0,0);return next}
function choosePlan(plans:Plan[],now:Date){if(!plans.length)return null;const monday=startOfDay(now);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));const key=monday.toISOString().slice(0,10);return plans.find(p=>p.week_start===key)||plans.find(p=>p.week_start>key)||plans.at(-1)||null}
function formatWeek(value:string){const start=new Date(`${value}T12:00:00`);const end=new Date(start);end.setDate(end.getDate()+6);const f=new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short"});return `${f.format(start)} – ${f.format(end)}`}
function formatWhen(value?:string|null){if(!value)return "No time set";return new Intl.DateTimeFormat("en-GB",{weekday:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
function formatOrderDate(value?:string|null){if(!value)return "No order recorded";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${value}T12:00:00`))}
function titleCase(value:string){return value.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase())}
const relationshipWarmth:Record<string,number>={current:0,cooling:1,lapsed:2,prospect:3};
function compareAccounts(a:Account,b:Account){const territory=(one(a.territory)?.name||"").localeCompare(one(b.territory)?.name||"");const warmth=(relationshipWarmth[a.relationship_status]??99)-(relationshipWarmth[b.relationship_status]??99);return territory||warmth||a.name.localeCompare(b.name)}
type ProgressStatus="not_contacted"|"contacted"|"follow_up"|"complete";
function isProgressStatus(value:string):value is ProgressStatus{return ["not_contacted","contacted","follow_up","complete"].includes(value)}
