import Link from "next/link";
import { notFound } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase";
import { setAppointmentStatus } from "../actions";

export default async function AppointmentPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createSupabaseServerClient();
  const { data: appointment, error } = await supabase.from("appointments").select("id,account_id,contact_id,starts_at,ends_at,purpose,notes,status,account:accounts(id,name,town,postcode),contact:contacts(id,full_name)").eq("id", id).single();
  if (error || !appointment) notFound();
  const account = Array.isArray(appointment.account) ? appointment.account[0] : appointment.account;
  const contact = Array.isArray(appointment.contact) ? appointment.contact[0] : appointment.contact;
  return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-2xl px-4 py-4 sm:px-6"><Link href="/diary" className="text-sm font-medium text-slate-500">← Diary</Link><div className="mt-3 flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">{appointment.purpose || "Appointment"}</h1><p className="mt-1 text-sm text-slate-500">{account?.name}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold capitalize text-slate-600">{appointment.status}</span></div></div></header><main className="mx-auto max-w-2xl space-y-4 px-4 py-5 sm:px-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 sm:grid-cols-2"><Info label="When" value={formatWhen(appointment.starts_at, appointment.ends_at)} /><Info label="Contact" value={contact?.full_name || "—"} /><Info label="Location" value={[account?.town, account?.postcode].filter(Boolean).join(" · ") || "—"} /><Info label="Notes" value={appointment.notes || "—"} /></div></section>{appointment.status === "planned" && <div className="grid gap-2 sm:grid-cols-2"><Link href={`/appointments/${id}/edit`} className="flex h-12 items-center justify-center rounded-xl border border-slate-300 bg-white font-semibold">Reschedule / edit</Link><Link href={`/accounts/${appointment.account_id}/visit?appointment=${id}`} className="flex h-12 items-center justify-center rounded-xl bg-slate-950 font-semibold text-white">Log visit</Link><form action={setAppointmentStatus}><input type="hidden" name="appointment_id" value={id}/><input type="hidden" name="account_id" value={appointment.account_id}/><input type="hidden" name="status" value="cancelled"/><button className="h-12 w-full rounded-xl border border-rose-200 bg-rose-50 font-semibold text-rose-700">Cancel appointment</button></form><form action={setAppointmentStatus}><input type="hidden" name="appointment_id" value={id}/><input type="hidden" name="account_id" value={appointment.account_id}/><input type="hidden" name="status" value="no_show"/><button className="h-12 w-full rounded-xl border border-slate-300 bg-white font-semibold text-slate-600">Mark no-show</button></form></div>}</main></div>;
}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 whitespace-pre-wrap font-medium text-slate-800">{value}</p></div>}
function formatWhen(start:string,end?:string|null){const s=new Date(start);const date=new Intl.DateTimeFormat("en-GB",{weekday:"short",day:"numeric",month:"short"}).format(s);const st=new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit"}).format(s);const et=end?new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit"}).format(new Date(end)):null;return `${date} · ${st}${et?`–${et}`:""}`}
