import Link from "next/link";
import {createHash} from "node:crypto";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {readTakeOff,rootOf,volumeSummary,estimatedPackagingDate} from "@/lib/take-off";
import {saveRequest,approveRequest,linkPlan} from "./actions";
import {Submit} from "./submit";
import {QuantityGrid} from "./quantity-grid";
export const dynamic="force-dynamic";
const input="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2";
const fmt=(v:number|null)=>v==null?"Unknown":new Intl.NumberFormat("en-GB",{maximumFractionDigits:1}).format(v)+" L";
const phase:Record<string,string>={planned:"Planned brew",staging:"Staging",in_tank:"In tank",finished:"No longer in tank",cancelled:"Cancelled",unresolved:"Needs batch association"};
export default async function Page({searchParams}:{searchParams:Promise<{brew?:string;weeks?:string;history?:string;error?:string;saved?:string}>}){
 const query=await searchParams;const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/login");
 const {subjects,requests,packages,state,canApprove,loadedAt}=await readTakeOff(db);
 const weeks=[2,4,8,12].includes(Number(query.weeks))?Number(query.weeks):4;
 const cutoff=new Date(loadedAt+weeks*7*86400000).toISOString().slice(0,10);
 const roots=subjects.filter(s=>rootOf(s,subjects)===s.id);
 const live=roots.filter(s=>query.history==="1"||s.id===query.brew||(!s.missing&&(["staging","in_tank"].includes(s.phase)||(s.phase==="planned"&&(!s.brew_date||s.brew_date<=cutoff))))||requests.some(r=>!r.withdrawn&&rootOf(subjects.find(s=>s.id===r.subject_id)!,subjects)===s.id));
 live.sort((a,b)=>({in_tank:0,staging:1,planned:2}[a.phase]??3)-({in_tank:0,staging:1,planned:2}[b.phase]??3)||(a.brew_date||"").localeCompare(b.brew_date||""));
 const selected=live.find(s=>s.id===query.brew)||live[0];
 const group=selected?subjects.filter(s=>rootOf(s,subjects)===selected.id):[];
 const groupIds=new Set(group.map(s=>s.id));
 const rows=requests.filter(r=>groupIds.has(r.subject_id));
 // Hash the rows actually rendered, so a refresh between reads cannot bless an older form.
 const revisionContext=(items:{id:string;revision:number}[])=>createHash("md5").update([...items].sort((a,b)=>a.id.localeCompare(b.id)).map(r=>r.id+":"+r.revision).join(",")).digest("hex");
 const context=revisionContext(group);
 const requestsContext=revisionContext(rows.filter(r=>!r.withdrawn&&r.owner_id===user.id));
 const summary=volumeSummary(rows,packages,context||"",selected?.volume_litres??null);
 const stale=!state.snapshot_at||loadedAt-new Date(state.snapshot_at).getTime()>86400000||!!state.last_error;
 const editable=selected&&!selected.missing&&["planned","staging","in_tank"].includes(selected.phase)&&!!selected.product_id;
 const variants=selected?.product_id?await db.from("product_variants").select("package_id").eq("product_id",selected.product_id).eq("allow_sale",true):{data:[]};
 const allowed=new Set((variants.data||[]).map(v=>v.package_id));

 const events=selected?await db.from("take_off_events").select("id,action,created_at,details").in("subject_id",[...groupIds]).order("id",{ascending:false}).limit(25):{data:[]};
 return <main className="mx-auto max-w-7xl p-4 pb-12 text-slate-950 sm:p-8">
  <header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><Link href="/sales" className="text-sm underline">← Sales workspace</Link><h1 className="mt-3 text-3xl font-bold">Take Off Planning</h1><p className="mt-2 text-slate-600">ViewPlan brew plan and tank contents · Sales requirements · Head Brewer review</p></div><span className="rounded-full bg-slate-100 px-3 py-2 text-sm">{canApprove?"Head Brewer":"Sales"}</span></header>
  <p className={stale?"mb-4 rounded-xl bg-amber-100 p-3":"mb-4 text-sm text-slate-500"}>{state.snapshot_at?"ViewPlan checked "+new Date(state.snapshot_at).toLocaleString("en-GB",{timeZone:"Europe/London"})+" (UK time)":"Awaiting first ViewPlan sync"}{stale?" — source data needs refreshing; approval is unavailable.":""}</p>
  {query.error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-red-900">{query.error}</p>}
  {query.saved&&<p role="status" className="mb-4 text-green-800">Saved.</p>}
  <form className="mb-4 flex flex-wrap items-end gap-3"><label>Upcoming<select name="weeks" defaultValue={weeks} className={input}>{[2,4,8,12].map(n=><option key={n} value={n}>{n} weeks</option>)}</select></label><label className="pb-2"><input type="checkbox" name="history" value="1" defaultChecked={query.history==="1"}/> Include history / unresolved plans</label><button className="rounded-lg border px-4 py-2">Apply</button></form>
  {!live.length?<section className="rounded-xl border bg-white p-8"><h2 className="font-semibold">No brews to display yet</h2><p className="mt-2">Run the Take Off connector to load ViewPlan. Historical and unresolved plans are available using the filter above.</p></section>:<>
  <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-100"><tr>{["Beer / gyle","Stage","Brew date","Est. packaging","Vessel","Litres","Packaging requests"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{live.map(s=>{const req=requests.filter(r=>!r.withdrawn&&rootOf(subjects.find(x=>x.id===r.subject_id)!,subjects)===s.id);return <tr key={s.id} className={s.id===selected?.id?"border-t bg-rose-50":"border-t"}><td className="p-3"><Link className="font-semibold underline" href={"/take-off?brew="+s.id+"&weeks="+weeks+(query.history==="1"?"&history=1":"")}>{s.product_name}</Link><div>{s.gyle||"Gyle not assigned"}</div></td><td className="p-3">{s.missing?"Missing from source — review":phase[s.phase]}</td><td className="p-3 whitespace-nowrap">{s.brew_date||"Unknown"}</td><td className="p-3 whitespace-nowrap">{estimatedPackagingDate(s.brew_date,s.packaging_days)||"Unknown"}{s.packaging_days!=null&&<div className="text-xs text-slate-500">{s.packaging_days} fermentation days</div>}</td><td className="p-3">{s.vessels.map(v=>v.label).join(", ")||"Not assigned"}</td><td className="p-3 whitespace-nowrap">{fmt(s.volume_litres)}</td><td className="p-3">{req.length?req.map(r=>r.quantity+" × "+(packages.find(p=>p.id===r.package_id)?.name||"Unknown package")).join("; "):"None yet"}</td></tr>})}</tbody></table></div>
  {selected&&<section className="mt-6 rounded-2xl border bg-white p-4 sm:p-6"><h2 className="text-2xl font-semibold">{selected.product_name} · {selected.gyle||"Planned brew"}</h2><p className="mt-1 text-sm text-slate-500">{selected.source_link_conflict?"ViewPlan links this plan to a different beer — source review required":phase[selected.phase]} · requests stay with this brew through source changes.</p>
   <p className="mt-3 text-sm">Estimated packaging: <strong>{estimatedPackagingDate(selected.brew_date,selected.packaging_days)||"Unknown"}</strong>{selected.packaging_days!=null?" · "+selected.packaging_days+" fermentation days from ViewPlan":" · awaiting ViewPlan fermentation duration"}. This estimate is not a release or stock availability confirmation.</p>
   {editable&&<QuantityGrid key={selected.id+context+requestsContext} brew={selected.id} context={context||""} requestsContext={requestsContext||""} packages={packages.filter(p=>allowed.has(p.id)||rows.some(r=>!r.withdrawn&&r.package_id===p.id)).sort((a,b)=>a.name.localeCompare(b.name))} requests={rows} userId={user.id} available={selected.volume_litres} estimatedDate={estimatedPackagingDate(selected.brew_date,selected.packaging_days)}/>}
   <div className="my-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Requested output",fmt(summary.requested)],["Agreed output",fmt(summary.agreed)],["Estimated beer required",fmt(summary.input)],["Remaining after approvals",fmt(summary.remaining)]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-100 p-3"><p className="text-xs text-slate-600">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>)}</div>
   <p className="text-sm text-slate-600">Remaining uses only current valid approvals and their explicit loss allowances. {summary.pending} request(s) await review. These figures do not reserve stock. Source volume changes invalidate previous approval calculations.</p>
   {summary.remaining!=null&&summary.remaining<0&&<p role="alert" className="mt-3 font-semibold text-red-800">Agreed packaging exceeds the source volume. Review the split.</p>}
   {group.some(s=>s.source_take_off.length>0)&&<details className="my-4 rounded-lg bg-amber-50 p-3"><summary>Existing ViewPlan take-off quantities — shown separately, not added to Sales demand</summary>{group.flatMap(s=>s.source_take_off).map((r,i)=><p key={i}>{r.take_off_qty} × {r.packaging_type} · {r.is_processed?"processed":"not processed"}</p>)}</details>}
   <div className="my-4 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="mb-2 text-left font-semibold">Packaging split</caption><thead><tr><th className="p-2">Package</th><th className="p-2">Requested units</th><th className="p-2">Reviewed units</th><th className="p-2">Awaiting decision</th></tr></thead><tbody>{packages.filter(p=>rows.some(r=>!r.withdrawn&&r.package_id===p.id)).map(p=>{const rs=rows.filter(r=>!r.withdrawn&&r.package_id===p.id);return <tr key={p.id} className="border-t"><td className="p-2">{p.name}</td><td className="p-2">{rs.reduce((n,r)=>n+r.quantity,0)}</td><td className="p-2">{rs.filter(r=>r.approval_context===context).reduce((n,r)=>n+(r.approved_quantity||0),0)}</td><td className="p-2">{rs.filter(r=>r.approved_quantity==null||r.approval_context!==context).length} request(s)</td></tr>})}</tbody></table></div>
<details className="mt-5"><summary className="cursor-pointer font-semibold">Saved requests and Head Brewer review ({rows.length})</summary>{rows.map(r=>{const approved=r.approved_quantity!=null&&r.approval_context===context;const canEdit=r.owner_id===user.id||canApprove;return <article key={r.id} className="mt-5 rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{r.quantity} × {packages.find(p=>p.id===r.package_id)?.name} · needed {r.required_by}</h3><span>{r.withdrawn?"Withdrawn":approved?"Reviewed":r.approved_quantity!=null?"Brew changed — review again":"Awaiting Head Brewer"}</span></div><p className="mt-2 text-xs text-slate-500">Requested by {r.owner_label}</p><p className="mt-2 whitespace-pre-wrap text-sm">{r.notes}</p>{r.approved_quantity!=null&&<p className="mt-2 text-sm">Last decision: {r.approved_quantity} units by {r.approved_date}; extra beer allowance {r.extra_input_percent}%. {r.response}</p>}
    {!r.withdrawn&&canEdit&&<details className="mt-3"><summary className="cursor-pointer text-sm underline">Edit or withdraw requirement</summary><form action={saveRequest} className="mt-3 grid gap-3 sm:grid-cols-2"><input type="hidden" name="brew" value={selected.id}/><input type="hidden" name="subject" value={r.subject_id}/><input type="hidden" name="id" value={r.id}/><input type="hidden" name="revision" value={r.revision}/><input type="hidden" name="package" value={r.package_id}/><input type="hidden" name="account" value={r.account_id||""}/><label>Units<input className={input} name="quantity" type="number" min="1" step="1" defaultValue={r.quantity} required/></label><label>Required by<input className={input} name="date" type="date" defaultValue={r.required_by} required/></label><label>Notes<textarea className={input} name="notes" maxLength={2000} defaultValue={r.notes}/></label><label className="self-center"><input name="withdraw" value="true" type="checkbox"/> Withdraw this request</label><Submit>Save requirement</Submit></form></details>}
    {!r.withdrawn&&canApprove&&editable&&!stale&&<details className="mt-3"><summary className="cursor-pointer text-sm font-semibold underline">Head Brewer review</summary><form action={approveRequest} className="mt-3 grid gap-3 sm:grid-cols-2"><input type="hidden" name="brew" value={selected.id}/><input type="hidden" name="id" value={r.id}/><input type="hidden" name="revision" value={r.revision}/><input type="hidden" name="context" value={context||""}/><label>Approved units (0 to decline)<input className={input} name="quantity" type="number" min="0" step="1" defaultValue={r.approved_quantity??r.quantity} required/></label><label>Agreed date<input className={input} name="date" type="date" defaultValue={r.approved_date||r.required_by} required/></label><label>Extra beer allowance %<input className={input} name="extra" type="number" min="0" max="100" step="0.1" defaultValue={r.extra_input_percent??""} placeholder="Enter explicitly, including 0" required/><span className="text-xs">Beer required = output litres × (1 + allowance / 100).</span></label><label>Response / constraints<textarea className={input} name="response" maxLength={2000} defaultValue={r.response}/></label><Submit>Confirm decision</Submit></form></details>}
   </article>})}</details>
   {!selected.product_id&&<p className="mt-4 text-amber-900">Product mapping is missing. Refresh the products connector before adding requirements.</p>}
   {canApprove&&selected.kind==="plan"&&!selected.source_link_key&&!selected.manual_batch_id&&<details className="mt-6"><summary>Associate this plan with an actual batch</summary><form action={linkPlan} className="mt-3 grid gap-3"><input type="hidden" name="plan" value={selected.id}/><input type="hidden" name="revision" value={selected.revision}/><label>Exact batch<select className={input} name="batch" required defaultValue=""><option value="" disabled>Verify against ViewPlan before selecting</option>{subjects.filter(b=>b.kind==="batch"&&b.source_product_id===selected.source_product_id).map(b=><option key={b.id} value={b.id}>{b.gyle||"No gyle"} · {b.brew_date} · {b.vessels.map(v=>v.label).join(", ")}</option>)}</select></label><label>Reason / evidence<input className={input} name="reason" minLength={5} maxLength={1000} required/></label><Submit>Confirm batch association</Submit></form></details>}
   <details className="mt-6"><summary>Recent change history</summary>{(events.data||[]).map(e=><p key={e.id} className="mt-2 text-sm">{new Date(e.created_at).toLocaleString("en-GB")} · {e.action.replaceAll("_"," ")}{e.details?.reason?" — "+e.details.reason:""}
{e.action==="source_changed"&&<span> · date {e.details.before?.brew_date||"unknown"} → {e.details.after?.brew_date||"unknown"}; volume {fmt(e.details.before?.volume_litres??null)} → {fmt(e.details.after?.volume_litres??null)}; stage {e.details.before?.phase} → {e.details.after?.phase}</span>}
{["requested","reviewed","withdrawn"].includes(e.action)&&<span> · {e.details.quantity} requested units, needed {e.details.required_by}{e.details.approved_quantity!=null?"; "+e.details.approved_quantity+" reviewed units by "+e.details.approved_date:""}{e.details.response?" · "+e.details.response:""}</span>}</p>)}</details>
  </section>}</>}
 </main>;
}
