import Link from "next/link";
import { notFound } from "next/navigation";
import { AccountTimeline } from "@/components/account-timeline";
import { BottomNav } from "@/components/bottom-nav";
import { createSupabaseServerClient } from "@/lib/supabase";

export default async function AccountDetailPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;
  const supabase=await createSupabaseServerClient();
  const {data:account,error}=await supabase.from("accounts").select(`*, territory:territories(id,name), sales:account_sales_snapshot(*), contacts(*)`).eq("id",id).single();
  if(error||!account)notFound();
  const [{data:visits},{data:tasks},{data:appointments}]=await Promise.all([
    supabase.from("visits").select("id,completed_at,notes,outcome,contact:contacts(full_name),salesperson:profiles(full_name,email)").eq("account_id",id).order("completed_at",{ascending:false}).limit(40),
    supabase.from("tasks").select("id,title,task_type,due_at,status,completed_at,notes,created_at").eq("account_id",id).order("created_at",{ascending:false}).limit(40),
    supabase.from("appointments").select("id,starts_at,purpose,status,notes").eq("account_id",id).order("starts_at",{ascending:false}).limit(40),
  ]);
  const sales=Array.isArray(account.sales)?account.sales[0]:account.sales;
  const territory=Array.isArray(account.territory)?account.territory[0]:account.territory;
  const contacts=[...(account.contacts||[])].sort((a,b)=>{if(a.is_primary!==b.is_primary)return a.is_primary?-1:1;return(a.brewery_contact_slot||99)-(b.brewery_contact_slot||99)});
  const primary=contacts.find(c=>c.is_primary)||contacts[0];
  const phone=primary?.phone||primary?.mobile||account.phone||account.mobile;
  const email=primary?.email||account.email;
  const address=[account.address_line_1,account.address_line_2,account.town,account.county,account.postcode].filter(Boolean).join(", ");
  const mapHref=address?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`:null;
  const upcoming=(appointments||[]).filter(a=>a.status==="planned"&&new Date(a.starts_at)>=new Date()).sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime()).slice(0,5);
  const openTasks=(tasks||[]).filter(t=>t.status==="open").sort((a,b)=>(a.due_at||"9999").localeCompare(b.due_at||"9999")).slice(0,10);

  return <div className="min-h-screen bg-slate-50 pb-24 text-slate-950 md:pb-10">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-5xl px-4 py-4 sm:px-6">
      <Link href="/accounts" className="text-sm font-medium text-slate-500">← Accounts</Link>
      <div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{account.name}</h1><StatusBadge status={account.relationship_status}/></div><p className="mt-1 text-sm text-slate-500">{[account.classification,account.town,account.postcode].filter(Boolean).join(" · ")}</p></div>
      <div className="flex flex-wrap gap-2"><Link href={`/accounts/${account.id}/appointment`} className="inline-flex h-10 items-center rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-700">Appointment</Link><Link href={`/accounts/${account.id}/visit`} className="inline-flex h-10 items-center rounded-xl bg-slate-950 px-4 text-sm font-semibold text-white">Log visit</Link></div></div>
      <div className="mt-4 grid grid-cols-2 gap-2 sm:flex"><QuickAction label="Call" href={phone?`tel:${phone}`:null}/><QuickAction label="Email" href={email?`mailto:${email}`:null}/><QuickAction label="Navigate" href={mapHref} external/><QuickAction label="New appointment" href={`/accounts/${account.id}/appointment`}/></div>
      {(phone||email)&&<p className="mt-2 text-xs text-slate-400">Quick actions use {primary?.full_name?`${primary.full_name} first, then account details`:"the account contact details"}.</p>}
    </div></header>
    <main className="mx-auto grid max-w-5xl gap-4 px-4 py-4 sm:px-6 lg:grid-cols-[1.2fr_0.8fr]"><div className="space-y-4">
      <Section title="Account"><div className="grid gap-4 sm:grid-cols-2"><Info label="Address" value={formatAddress(account)} multiline/><Info label="Territory" value={territory?.name||account.brewery_location_zone||"—"}/><Info label="Phone" value={account.phone||account.mobile||"—"} href={account.phone||account.mobile?`tel:${account.phone||account.mobile}`:undefined}/><Info label="Email" value={account.email||"—"} href={account.email?`mailto:${account.email}`:undefined}/><Info label="Website" value={account.website||"—"} href={normaliseUrl(account.website)}/><Info label="BMS status" value={[account.brewery_status,account.brewery_available===false?"Unavailable":null].filter(Boolean).join(" · ")||"—"}/></div></Section>
      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold uppercase tracking-[0.08em] text-slate-500">Contacts{contacts.length?` (${contacts.length})`:""}</h2><Link href={`/accounts/${account.id}/contacts`} className="text-xs font-semibold text-slate-600 hover:underline">Manage contacts</Link></div>{contacts.length?<div className="divide-y divide-slate-100">{contacts.map(c=><div key={c.id} className="py-3 first:pt-0 last:pb-0"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{c.full_name||"Unnamed contact"}</p>{c.is_primary&&<span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-slate-600">Primary</span>}</div>{c.job_title&&<p className="mt-0.5 text-xs text-slate-500">{c.job_title}</p>}{c.email&&<a href={`mailto:${c.email}`} className="mt-1 block text-sm text-slate-600 hover:underline">{c.email}</a>}{(c.phone||c.mobile)&&<a href={`tel:${c.phone||c.mobile}`} className="mt-0.5 block text-sm text-slate-600 hover:underline">{c.phone||c.mobile}</a>}</div><div className="flex gap-2">{(c.phone||c.mobile)&&<a href={`tel:${c.phone||c.mobile}`} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700">Call</a>}{c.email&&<a href={`mailto:${c.email}`} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700">Email</a>}</div></div></div>)}</div>:<p className="text-sm text-slate-500">No contacts recorded.</p>}</section>
      <Section title="Timeline"><AccountTimeline visits={visits||[]} appointments={appointments||[]} tasks={tasks||[]}/></Section>
    </div><div className="space-y-4">
      {upcoming.length?<Section title={`Upcoming appointments (${upcoming.length})`}><div className="space-y-3">{upcoming.map(a=><Link key={a.id} href={`/appointments/${a.id}`} className="block rounded-xl bg-slate-50 p-3"><p className="font-semibold text-slate-800">{a.purpose||"Sales visit"}</p><p className="mt-1 text-xs text-slate-500">{formatDateTime(a.starts_at)}</p></Link>)}</div></Section>:null}
      {openTasks.length?<Section title={`Open follow-ups (${openTasks.length})`}><div className="space-y-3">{openTasks.map(t=><div key={t.id} className="rounded-xl bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-slate-800">{t.title}</p><span className="rounded-full bg-white px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-slate-500 ring-1 ring-slate-200">{t.task_type}</span></div><p className="mt-1 text-xs text-slate-500">Due {formatDateTime(t.due_at)}</p></div>)}</div></Section>:null}
      <Section title="Sales snapshot"><div className="grid grid-cols-2 gap-4"><Metric label="Lifetime sales" value={formatCurrency(sales?.total_spend)}/><Metric label="Orders" value={sales?.total_orders?.toLocaleString("en-GB")||"—"}/><Metric label="Average order" value={formatCurrency(sales?.average_order_value)}/><Metric label="Largest order" value={formatCurrency(sales?.maximum_order_value)}/></div><div className="mt-5 grid gap-3 border-t border-slate-100 pt-4 text-sm"><DateRow label="First order" value={sales?.first_order_date}/><DateRow label="Last order" value={sales?.last_order_date}/><DateRow label="Last delivery" value={sales?.last_delivery_date}/><DateRow label="Last visit" value={account.last_visit_at?.slice(0,10)}/></div></Section>
      <Section title="Field sales"><div className="grid gap-3 text-sm"><Info label="Customer rep" value={account.brewery_customer_rep||"—"}/><Info label="Telesales rep" value={account.brewery_telesales_rep||"—"}/><Info label="Preferred contact" value={account.preferred_contact_method||"—"}/><Info label="Next BMS call" value={formatDate(account.brewery_next_call_date)}/><Info label="Call schedule" value={[account.brewery_call_days,account.brewery_call_time,account.brewery_call_schedule].filter(Boolean).join(" · ")||"—"}/></div></Section>
    </div></main><BottomNav active="Accounts"/></div>;
}
function QuickAction({label,href,external=false}:{label:string;href:string|null;external?:boolean}){const cls="inline-flex h-11 items-center justify-center rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm font-semibold text-slate-800 hover:bg-slate-100";return href?<a href={href} target={external?"_blank":undefined} rel={external?"noreferrer":undefined} className={cls}>{label}</a>:<span className={`${cls} cursor-not-allowed opacity-40`}>{label}</span>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><h2 className="mb-4 text-sm font-semibold uppercase tracking-[0.08em] text-slate-500">{title}</h2>{children}</section>}
function Info({label,value,href,multiline=false}:{label:string;value:string;href?:string;multiline?:boolean}){return <div><p className="text-[11px] font-medium uppercase tracking-wide text-slate-400">{label}</p>{href?<a href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} className={`mt-1 block font-medium text-slate-800 hover:underline ${multiline?"whitespace-pre-line":"truncate"}`}>{value}</a>:<p className={`mt-1 font-medium text-slate-800 ${multiline?"whitespace-pre-line":""}`}>{value}</p>}</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-medium uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-lg font-semibold tracking-tight">{value}</p></div>}
function DateRow({label,value}:{label:string;value?:string|null}){return <div className="flex items-center justify-between gap-4"><span className="text-slate-500">{label}</span><span className="font-medium">{formatDate(value)}</span></div>}
function StatusBadge({status}:{status:string|null}){const styles:Record<string,string>={current:"bg-emerald-50 text-emerald-700 ring-emerald-600/20",cooling:"bg-amber-50 text-amber-700 ring-amber-600/20",lapsed:"bg-orange-50 text-orange-700 ring-orange-600/20",dormant:"bg-slate-100 text-slate-600 ring-slate-500/20",prospect:"bg-blue-50 text-blue-700 ring-blue-600/20",closed:"bg-rose-50 text-rose-700 ring-rose-600/20"};const key=status||"dormant";return <span className={`rounded-full px-2 py-0.5 text-[11px] font-semibold capitalize ring-1 ring-inset ${styles[key]||styles.dormant}`}>{key}</span>}
function formatAddress(a:{address_line_1?:string|null;address_line_2?:string|null;town?:string|null;county?:string|null;postcode?:string|null}){return[a.address_line_1,a.address_line_2,a.town,a.county,a.postcode].filter(Boolean).join("\n")||"—"}
function formatDate(v?:string|null){if(!v)return"—";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${v.slice(0,10)}T00:00:00`))}
function formatDateTime(v?:string|null){if(!v)return"—";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}
function formatCurrency(v?:number|null){if(v===null||v===undefined)return"—";return new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(v)}
function normaliseUrl(v?:string|null){if(!v)return undefined;return /^https?:\/\//i.test(v)?v:`https://${v}`}
